/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.toolsandenvironmentfinal;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Khang
 */
public class SearchEmployeeForm extends javax.swing.JFrame {
    private String header[] = {"Code","Full name"," Birthday","Gender","Address","Phone"};
    private DefaultTableModel tbModel = new DefaultTableModel(header,0);
    
    
    /**
     * Creates new form SearchEmployeeForm
     */
    public SearchEmployeeForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tfSearchFullName = new javax.swing.JTextField();
        tfSearchCode = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tfEmpTable = new javax.swing.JTable();
        btnSearch = new javax.swing.JButton();
        btnSearchClose = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnDetail = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("Code");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 0));
        jLabel2.setText("Full name");

        tfEmpTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Code", "Name", "Birthday", "Gender", "Address", "Phone"
            }
        ));
        tfEmpTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tfEmpTableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tfEmpTable);

        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        btnSearchClose.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnSearchClose.setText("Close");
        btnSearchClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchCloseActionPerformed(evt);
            }
        });

        btnDelete.setText("Delete");

        btnEdit.setText("Edit");

        btnDetail.setText("Detail");
        btnDetail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDetailActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2)
            .addGroup(layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfSearchCode, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tfSearchFullName, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnDetail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnSearch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(44, 44, 44)
                .addComponent(btnDelete)
                .addGap(31, 31, 31)
                .addComponent(btnEdit)
                .addGap(45, 45, 45)
                .addComponent(btnSearchClose)
                .addGap(27, 27, 27))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tfSearchCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tfSearchFullName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearch)
                    .addComponent(btnSearchClose, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDelete)
                    .addComponent(btnEdit))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnDetail)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void SelectEmployee(String sql){
         try {
            Ultility util = new Ultility();
            Connection con = util.connectionDB();
            Statement st = con.createStatement();
            
            ResultSet rs = st.executeQuery(sql);
            if(!rs.isBeforeFirst()){
                JOptionPane.showMessageDialog(this, "No data!","Message",JOptionPane.INFORMATION_MESSAGE);
                return ;
            }
             tbModel.setRowCount(0);
             while(rs.next()){
                 Vector data = new Vector();
                 data.add(rs.getString("code"));
                 data.add(rs.getString("fullname"));
                 data.add(rs.getString("birthday"));
                 data.add(rs.getString("gender"));
                 data.add(rs.getString("address"));
                 data.add(rs.getString("phone"));
                 tbModel.addRow(data);
             }
             this.tfEmpTable.setModel(tbModel);
            con.close();
        }catch (Exception ex) {
            JOptionPane.showMessageDialog(this,ex.getMessage(),"Message",JOptionPane.INFORMATION_MESSAGE);
        }
    }
    
    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
        String sql = "select * from employees where code like '%" + tfSearchCode.getText() + "%' AND fullname like '%" + tfSearchFullName.getText() +"%'";
        this.SelectEmployee(sql);
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnSearchCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchCloseActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnSearchCloseActionPerformed

    private void tfEmpTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfEmpTableMouseClicked
        // TODO add your handling code here:
        tfSearchCode.setText(tfEmpTable.getValueAt(tfEmpTable.getSelectedRow(),0).toString());
    }//GEN-LAST:event_tfEmpTableMouseClicked

    private void btnDetailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDetailActionPerformed
        // TODO add your handling code here:
        if (tfEmpTable.getSelectedRow() == -1)
        {
            JOptionPane.showMessageDialog(this,"No rows selected","Message",JOptionPane.INFORMATION_MESSAGE);
            return;
        }
         ArrayList<String> employeeDetails = new ArrayList<>();
         for ( int  i= 0; i< 6;i++){
             employeeDetails.add(tfEmpTable.getValueAt(tfEmpTable.getSelectedRow(),i).toString());
         }
         new AddNewEmployeeForm(employeeDetails).setVisible(true);
         this.dispose();
         
         
    }//GEN-LAST:event_btnDetailActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnDetail;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnSearchClose;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable tfEmpTable;
    private javax.swing.JTextField tfSearchCode;
    private javax.swing.JTextField tfSearchFullName;
    // End of variables declaration//GEN-END:variables
}
